"""add_email_to_project_members

Revision ID: a630cfe2a238
Revises: 917395cbaa09
Create Date: 2026-04-30 11:18:27.368149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a630cfe2a238'
down_revision: Union[str, None] = '917395cbaa09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('email', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'email')
    # ### end Alembic commands ###
